services:
  lb:
    build:
      context: ./lb
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - UPSTREAMS=/sockets/api1.sock,/sockets/api2.sock
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30M"
    logging:
      driver: none

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INDEX_PATH=/index/index.bin
      - NPROBE=5
      - ADAPTIVE=1
      - REPAIR_MIN=1
      - REPAIR_MAX=4
      - MAX_REPAIR=91
      - SOCKET_PATH=/sockets/api1.sock
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160M"
    logging:
      driver: none

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INDEX_PATH=/index/index.bin
      - NPROBE=5
      - ADAPTIVE=1
      - REPAIR_MIN=1
      - REPAIR_MAX=4
      - MAX_REPAIR=91
      - SOCKET_PATH=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160M"
    logging:
      driver: none

volumes:
  sockets:
